export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body>
        <header>
          Header
        </header>
        {children}
        <footer>
          Footer
        </footer>
        </body>
    </html>
  )
}
